### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by pantchox** [yoshikischmitz/workflowy-clone#1]
Hi,

thanks for this great clone starter, it works very well and mimics workflowy in nice elegant way.
I am working on doing bookmarking manager (still not ready and will take time..) and i might use part of your code and prob' will want to extend it to add more actions such as delete, collapse etc.

Would like to know the license, thanks!

**Comment by yoshikischmitz** [comment]
Hi pantchox,

Thanks for your opening this issue. I went ahead and added the MIT license to this project so feel free to use it however you want! Excited to see what you do with it!
